spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/schedulerdb?serverTimezone=Asia/Seoul
      username: develop
      password: go8426!@
      driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: never
  hibernate:
    ddl-auto: none
  batch:
    job:
      names: ${job.name:NONE}

public:
  data:
    key: mSMTdcOf2M60Eh4mnTVPd1HYE5yykdwAzGrFzBGUzGXt9VXBLTOB7Opa9oP4xJUc2odLnRuZyUH0SjzoimicWQ%3D%3D
    url: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo